### ISSUE TITLE
Add explanation on scoring

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-backend#200]
As an option, add an "explain" (same level as scores) as a dictionary : 

```
explain:
  name:
    particles: true
    nameSwap: true
    first:
      levenshteinScore: 0.97
      soundexScore: 1
    last: ...
```

Could be used to display statistics when annotating in the UI.
Should be optional for performance issues.
